-- Member & household address fields for pastoral visitation
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "stateRegion" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'India';
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "addressLine1" TEXT;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "stateRegion" TEXT;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'India';
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Family" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
