/**
 * Generate RUNTIME_ACTIVATION_REPORT.md from live /health/routes + verify:v1.
 * Run with API up: npm run report:runtime
 */
import '../utils/loadEnv.ts';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const PORT = process.env.PORT || '4002';
const HOST = process.env.RUNTIME_REPORT_HOST || '127.0.0.1';
const healthUrl = `http://${HOST}:${PORT}/health`;
const routesUrl = `http://${HOST}:${PORT}/health/routes`;

async function main() {
  let classification: 'READY' | 'WARNING' | 'BLOCKED' = 'BLOCKED';
  const sections: string[] = [];

  let health: Record<string, unknown> = {};
  let routes: Record<string, unknown> = {};

  try {
    const h = await fetch(healthUrl);
    health = (await h.json()) as Record<string, unknown>;
    sections.push(`- **Health:** ${h.ok ? 'OK' : `HTTP ${h.status}`}`);
  } catch (e) {
    sections.push(`- **Health:** unreachable (${e instanceof Error ? e.message : String(e)})`);
  }

  try {
    const r = await fetch(routesUrl);
    routes = (await r.json()) as Record<string, unknown>;
    const probes = (routes.probes as Array<{ ok: boolean }>) ?? [];
    const ok = probes.filter((p) => p.ok).length;
    const total = probes.length;
    sections.push(`- **Route probes:** ${ok}/${total}`);
    if (r.ok && routes.status === 'ready') classification = 'READY';
    else if (r.ok) classification = 'WARNING';
  } catch (e) {
    sections.push(`- **Routes:** unreachable (${e instanceof Error ? e.message : String(e)})`);
  }

  const failures = (routes.failures as string[]) ?? [];
  if (failures.length > 0) {
    classification = 'BLOCKED';
  }

  const md = `# Kingdom Church OS — Runtime Activation Report

**Generated:** ${new Date().toISOString()}  
**Classification:** ${classification}

## Runtime snapshot

${sections.join('\n')}

- **Version:** ${String(health.version ?? routes.version ?? 'unknown')}
- **Boot ID:** ${String(health.bootId ?? routes.bootId ?? '—')}
- **Database:** ${String(health.database ?? '—')}

## Mounted route groups

${((routes.mountedGroups as string[]) ?? []).map((g) => `- ${g}`).join('\n') || '_Unavailable_'}

## Probe results

| Probe | Status | OK |
|-------|--------|-----|
${(((routes.probes as Array<{ label: string; path: string; status: number; ok: boolean }>) ?? [])
  .map((p) => `| ${p.label} | ${p.path} | ${p.status} | ${p.ok ? '✓' : '✗'} |`)
  .join('\n') || '| — | — | — | — |')}

## Failures

${failures.length ? failures.map((f) => `- ${f}`).join('\n') : '_None_'}

## Operational classification

| Status | Meaning |
|--------|---------|
| **READY** | All V1 critical routes mounted and reachable |
| **WARNING** | API up but route table degraded |
| **BLOCKED** | Stale process, partial startup, or unreachable API |

## Startup commands

\`\`\`bash
npm run runtime:clean
npm run dev:server:fresh
npm run verify:v1
\`\`\`

## Production requirements

- \`DATABASE_URL\`, \`JWT_SECRET\`, \`REDIS_URL\` (production)
- \`npm run db:migrate\` before first boot
- \`npm run deploy:production\` for gated promotion

---

*Auto-generated by \`npm run report:runtime\`*
`;

  const outPath = join(process.cwd(), 'RUNTIME_ACTIVATION_REPORT.md');
  writeFileSync(outPath, md, 'utf8');
  console.log(`[report:runtime] Wrote ${outPath} (${classification})`);
  if (classification === 'BLOCKED') process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
